language: node_js
node_js:
- 8.4.0
sudo: required
cache:
  directories:
  - node_modules
before_install:
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
- npm i -D uglifyjs-webpack-plugin
install:
- npm install
- npm run ng-deploy
- ls -l
script:
- docker build -t $DOCKER_USERNAME/se234-lab10-client .
- docker push $DOCKER_USERNAME/se234-lab10-client
service: docker
env:
  global:
  - secure: w6R93Bi5/kjeYp5uwogA15PpaGdDMWo3U1icTawosJ3pYV8nrIN64OUHFX5HPmgvHM0gJ/spncB8KRpUZjC4kR5CaEVHOKZuj2L0C560tfbsFKlfT3vPHAZT4XmgW35XRE8hRbPsLn6ZKtKyqmAagATZjZRl8558tO2WzRcL/Gssov0J6rYOBJexpfYPEA2fL7S7RulQxv2GEfBCJMKPl6+DlywCxwdbXVGNeF5G6uYxvXHdJ3VkJWYHrAmZsJfRiiq9S638DustA5e+7TSaTaNK2U8S9NxvzpUKkezlcD0l6BPYdTjo4CYEha0UCARGs65hhgZaeUeoZlhOo1IC3FzizW0wP7CkW86vb7PgsqHm4zc8bEnj4RadUVRbAJXH0G8Dczp1XyaHF12is2mgfm0KkE8DERK4U8bYmfjCZu1dRNiv0Y9JStZ9aRMnRHVpHpMJj8G2nKgyIaeksEcEz6Ah9WcCHC253Sjg8le/67V63+FqZ+feMvg5SC0uytWax4HdFYEZNDd97mg3fzwgg02orWUKTRRcEpE4FWvIPqmsahbqetbVqaNi/UBkw+6uRX+fRqutk8UmnfzYyTIg6yQh4mWXzcYrsTPzQUIayy0JBuKI5I0zCUcBv9TM0tO9POe0LCmR7nE4wTRJl7jLRX/UWfXeLn33yGSKfZAtu5Y=
  - secure: TMRYlIwnIq8gumhsGyXXEPeHQov6FwVIx0dzr9QSDfHpx9ZIHo5f0LWYX7h2zLOoRduSQ5L3+ycD0QCnWBffhQYiRjt/FUU9vgkdJeM+Yh9pJwd0AisrnP1ITIFbLqaGZF9IdKT1mcsSoeeQtttLmNwHC3bzTkz2v2398xlLoMSW5ELv8XZguhw305cbYCV7Rri09mlVoKxqHGjiIlkq5O9qQa2rVdZ8e3zuEcjihJYEOmEZhlAXVDmrmnuBEFK7orDXcrcaHu1x8FDLLFe0eP+fmHpq99+AcKbvgpkKZqggAkVyxcXwBuyZI6+AcK48r8Po9eJRhBvvZxJ7zEhEEWDtJSdruISJoAC1nxHqDK57C0MjQr0VKnjQ9ubqQ9qnOmNDbXphNPP/phzqZCaXTQhLKkWZCNfzcEMq48tcDUWPyIMxXsdJxnvkKZZXkXnAItjhfz5Xl7Za+GbOd3hpXusrUzZ0Wb5581N/PrCZGH51J+JzRiajM8oVRJrV2EAAs1Giye0lId1mJTqJUIuK8PVIB/t52gSmQ9t/VKRq5ui1rJCB9EDNb0Ptwc9Rw2a1LFc0a0yp/6PCYdN9sa7FnCAnRX/+mNLlmuVn3XZU1ZQ++42+Ym6ekgFzBKg0/rRsxSgIvAF8b/OHGxtYljDn0CvZKv4lMttBGIQoDSsjPsI=
  - secure: DRKxi1xuz8ZK5hQbSW8Ob5/A+LGPXRnj6SozTc5HxfZa/6kqM2mcvoQHSaqwQDK4A5PowulzHGhj3+qY4tkkymPVRM2kbPifTHJmiKeMuKl/yPJhmfnctncAsbCwEUl4A87C9Sp8pjh+MFHGbdVD3G+F9A2GW2qbw/4xGWPoHh1ypSxOkMVaZQcCjMzpLaieub/64lFvxUrY0p1bRV7UQgWcOKBg10AA0A7S2kDUpzpBWud0ybZacnYYSsJpD+1n85d5Q4JlW7H185jyVtNxRImef1YkJXDJKsc+LevP5lHqp4AGiMNO/emp0Mk2S0QdSgp0mMOQAolTTruLUVQM9ZJrHcXq0fFV8XeFKewQnKRsZk6wkD39+6JhsWR654l69ocRjPt1U/htHZxlUNYSblc2OCnHCf+PnkqFbqvzNy6c3eYo3pFj9OIQDh+El4Ddv7sGY4qOMXtmYq/3/fHMSHLm7dglIcBgzSCeOQWYlu7mJl3AQpcGZqjiw0WMeBEtvPe6FS/qptcxnSLJeJwMc373nzOI7XyGFoMfzSwYaaRnEPX62nI5NVGwkUNiMTqCWWgbDinLSEMQHd2VxgsHjFPVMrqnn8xOLV5xObK+iOTxnZewL6Img4gE/6qILTI2Z+FErIcT9GQR3iEp0NvI6FGJHT6nuABcctskRYzVews=
