language: node_js
node_js:
- 8.4.0
sudo: required
cache:
  directories:
  - node_modules
before_install:
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
- npm i -D uglifyjs-webpack-plugin
install:
- npm install
- npm run ng-deploy
- ls -l
script:
- docker build -t $DOCKER_USERNAME/se234-lab10-client .
- docker push $DOCKER_USERNAME/se234-lab10-client
service: docker
env:
  global:
  - secure: NP2VtOsQLGpdQBkiGTvLrBMofW9UFRLo4FTlSnCR35sbzKEeCMo3P/ZbN0aOjci6afctHjYsL4Pk9c0tjBYdJQuaTlLSYKAP3weCihmIHaCuai3dIJWA+Le3nCdf5aXQIQB1Yuwy+iT5iVY+q6W8MsWP7AJPIIKAw9mndVwDyP9hcdMjh8BHEYhNMqzfPyKofWre7JrnubIt94jrQ8QQqZexApP/7UHYJFGZy2fvH48OGivmV7trU3xV2uyIFapDyhD5ldxhYgOvon2sRXVs1pbjDkrRoW5MIg1s2Lb4AfYGRU/BU374p5kSRq48UDgT5CcID/Dpgx4ThnoEj4B1PvTl2HXM/3/QKmKZdNCMtXdHQ5S6yH/QVgvJvCNZqy+i7M61YsDZP4KLNArh7RdQoKlO6qTTLy+Zobo2UxgmAJ/tnorEJoDcnfxKiE5ouaYMf82vzvVpDLKUXpoCrtCiiTAeeUZf3B8neLi9587I2SEzKPWN+hUguPIhOpTmb0uyubzC/YGyd0FkD3Ty/gSROMK1IlOCKhjgc5bicTOkABC+NDfz9CMTeoxaj001xPrhUzY4GMY+N/rKXONWZ2UQMizW5zf5+e9pu/UyGnLwV9AX5AYRYNYLJf4CyOAEKIaNY5uiBsdwwXKL0RNFc6S1h5K1meyZjJt9Ho+etvUutxg=
  - secure: AzYbL2ZCR2HsProofJnoOIKeDtt7X5CbtrzcynL6stypRcCBXOCyZOz51JnlAgkQjbKI+c1Nu5cDwcA/kYA9Tu8LPgGec8Tnq8pt/bZKQ6LRsH+sWD11RO75tbps9V10PWFaj1RenSZRp3egk55znP4HB2xE/ptrgjHhPAaQroNB16i7kF+M/ZIZqWfglf98bsi+ppUNPFfv2wU4bqAp4Bpwmp/+Qq+Y+XQUnsHk/Zit3HlfCgfh/HCOUutfSkCnxSbtL4Er3ghlORLhNXsNjlxwZGBBRSupoT1vU/CLk9dXBd4emf2F4Qplqay9vHl1cupBWljQV3jU/zjr64qcuA60LDsAr096O3WKRKEU4ZUAFYXqzJANl+ZjmDJwoU5KOU5Z6vfXVCe3q0YNpbqepFanIcg9uuWyK+jZLOHf0FTPXzOScaJXAM1U4falqZ3tRwe/BmS+s9Av67O1THK+ivjtqOC2Ezjv/uiiG7fQAYJQe3oJ28V2fjJcAG775z+7M1WR1DBCYVNU/cK3wu3fDjpU78yeFO0ZEH/tt8VB20TBenIaEkkQ1gJEMrFCyBczF7PGsbXagta4u5NJhw/E2yt+wjvmfeots6MezxqyXnJwJwdF+X6uM22HNINbfRoQWXylIWarGOzmb1nsWGdWtz4sXfKBjizwyQjHLilZQeA=
  - secure: PwtNgfFvXmMI1/l5c9z3rOKX62390TPdTWw/hdnD3knz/JRQIUSQdG9iEuCGnpVqajLWLHndXhE6ekAVvEcgWqHo495PDXw21COXW6nYybNuzynDZXS/4qdd8Jns3Bjw7SPWdh3FIkF3drmizioCS25pdQBkGuTj/x+l/9tnpbnpJ2FYzFhyvWQmoXPkrLd7HDyQ8SkBRo5BPO77o7UoUnEIMgfiseJ6AHkDutAiNABPEOFr1zQ4+DhbBP4mNZAjGldMDSPFjVvYqIdA8Sw1p2fGBvlZw0rgfxAs9R03krfELsS358D3wT6m/No9tRzIRAFCouW8CoVGhmS49FsRgvu4QwSyUD/CWz7aDecHn5nQ7DRoL2Tb4UCvXxkt494yB8ZJ9i5n9hShCcHzdMKbPCwlSzeOOcKDEs5bLgxyAVoKnJQyhlKKssgvc5kPG7CczglO84veKl+9XAuNAY7kPwuy3tV1ugCXaMWl+jEZ+tP0JFkbe4T6sjvm6ELEfv+NwwWXZwDEqi0gQQhQEexX6qmPy6kTVmNo+JS6VCbZrZohTGlCNzgdzqsqklF8M+HPT2kO7szEcxq3RRsJ+c3rRmRppNo9wpzhGxF/26RB0RpJAPxfUhjnHFvxLcCgxA3fA5Xe0pUf/agDUDWES/BlKBoLb3qcE/1OyeFfaDLEutE=
